development:
  adapter: mysql2
  database: foodbank_dev
  host: 127.0.0.1
  username: mike
  password: asdf1234
  timeout: 5000

test:
  adapter: mysql2
  database: foodbank_test
  host: 127.0.0.1
  username: mike
  password: asdf1234
  timeout: 5000

